apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sample-karate-doc"
  description: "sample-karate-doc"
  annotations:
    github.com/project-slug: rupesh-patil-22/sample-karate-doc
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: "eds"
